#%RAML 1.0 ResourceType
post:
  body:
    application/json:
      type: postOrganizationRequest
      example: !include ../examples/requests/postOrganizations.json
  responses:
    201:
      body:
        application/json:
          type: postOrganizationResponse
          example: !include ../examples/responses/postOrganizations.json
is:
              - clientCredentials   