#%RAML 1.0 DataType
type: object
properties:
  name:
    type: string
    required: true
  aceOrgId:
    type: number
    required: true
  customFieldname:
    type: string
    required: true
  aceLegacyId:
    type: number
    required: true
  erpAcctNo:
    type: string
    required: true
  acctStatus:
    type: string
    required: true
  building:
    type: string
    required: true
  timeZone:
    type: string
    required: true
  nationalAccount:
    type: boolean
    required: true
  idReq:
    type: boolean
    required: true
  address1:
    type: string
    required: true
  address2:
    type: string
    required: false
  address3:
    type: string
    required: false
  city:
    type: string
    required: true
  state:
    type: string
    required: true
  postalCode:
    type: string
    required: true
  country:
    type: string
    required: true
  billTo:
    type: boolean
    required: true
  shipTo:
    type: boolean
    required: true